use_frameworks!

platform :ios, '11.0'

target 'InputView_Example' do
  pod 'InputView', :path => '../'
  pod 'ExpressionManager'
  pod 'ContentSizeView'
  pod 'Util_V'
  pod 'SnapKit'
  pod 'LookinServer'
end
